name: dbebr_sqflite
description: DBEBr Framwork for Dart/Flutter (SQLite - package sqflite)
version: 0.0.1
repository: https://github.com/isaquepinheiro
publish_to: 'none'

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dbebr_core:
    path: ../dbebr_core
  sqflite: ^2.2.6
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
