name: dbebr_mysql1
description: DBEBr Framwork for Dart/Flutter (MySQL - package mysql1)
version: 0.0.1
homepage: https://github.com/isaquepinheiro
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  dbebr_core:
    path: ../dbebr_core
  meta: ^1.9.1
  mysql1: ^0.20.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
